### ISSUE TITLE
Bluetooth and WiFi not working after updating to macOS Sonoma 14.0

### ISSUE THREAD

**Issue by akibur-rohman** [jkaninda/Hackintosh-HP-EliteBook-830-G5-OC-Ventura#1]

**Comment by adam25255** [comment]
Because Sonoma dropped some chipsets.(even if you have BCM94360NG) Does in-place upgrade work?(really curious about this) https://www.reddit.com/r/hackintosh/comments/1721nh5/bcm94360ng_in_sonoma/
Sonoma Wifi fix.(BCM 802.11ac card)https://github.com/leocg/Hackintosh-Dell-G5-5590/blob/master/README.md#enabling-broadcom-wifi-with-sonoma

Broadcom card. https://www.ebay.com/itm/385378162648


Hope that helpúed.

**Comment by adam25255** [comment]
> Because Sonoma dropped some chipsets.(even if you have BCM94360NG) Does in-place upgrade work?(really curious about this) https://www.reddit.com/r/hackintosh/comments/1721nh5/bcm94360ng_in_sonoma/
> 
> Sonoma Wifi fix.(BCM 802.11ac card)https://github.com/leocg/Hackintosh-Dell-G5-5590/blob/master/README.md#enabling-broadcom-wifi-with-sonoma

Broadcom card. https://www.ebay.com/itm/385378162648
